import random

easy_behavioral_questions = [
    "Can you describe a time when you worked well in a team?",
    "Tell me about a time you had to complete a task within a deadline.",
    "Have you ever had to resolve a dispute between two friends or colleagues? What did you do?",
    "Describe a situation where you had to follow a set of guidelines or rules.",
    "Tell me about a project you are proud of. What was your role?",
    "Can you give an example of a time you took initiative?",
    "How do you handle receiving constructive feedback?",
    "Tell me about a time you had to learn something new on the job.",
    "Have you ever had to work closely with someone whose personality was different from yours?",
    "Describe a situation where you had to use your problem-solving skills.",
    "Tell me about a time you helped a team member who was struggling.",
    "Have you ever faced a difficult situation with a customer? How did you handle it?",
    "What do you do when you have a lot of tasks and feel overwhelmed?",
    "Describe a time when you had to work under pressure.",
    "Tell me about a situation where you had to be organized.",
    "Can you describe a time when you were a good listener?",
    "Have you ever had to persuade someone to see things your way?",
    "Tell me about a time you made a mistake. How did you handle it?",
    "Describe a situation where you had to take on a leadership role.",
    "Tell me about a time when you had to adapt to change.",
    "Can you share an example of when you had to be resourceful?",
    "Describe a situation where you had to work with limited resources.",
    "Tell me about a time you worked on improving a process.",
    "Have you ever been a part of a project that was behind schedule? What did you do?",
    "Describe a situation where you had to communicate clearly.",
    "Tell me about a time you had to prioritize tasks.",
    "Can you give an example of when you were reliable?",
    "Have you ever helped someone improve at their job? How?",
    "Tell me about a time you had to collaborate on a project.",
    "Describe a situation where you took ownership of a problem and solved it.",
    "Tell me about a time you received praise for your work.",
    "Can you share an example of a time you were punctual?",
    "Have you ever had to deal with a difficult team member?",
    "Tell me about a time you had to make a quick decision.",
    "Describe a situation where you had to show empathy.",
    "Tell me about a time you exceeded expectations.",
    "Can you share an experience when you had to be self-motivated?",
    "Describe a situation where you had to be patient.",
    "Tell me about a time you offered creative solutions to a problem.",
    "Have you ever had to communicate complex information? How did you go about it?",
    "Tell me about a time you were part of a successful team. What made it successful?",
    "Describe a situation where you had to multitask.",
    "Tell me about a time you faced a challenge and how you overcame it.",
    "Can you share an example of when you had to resolve a conflict?",
    "Describe a situation where you took the initiative to improve something at work.",
    "Tell me about a time you had to meet a strict quality standard.",
    "Can you give an example of a time you took on a challenging task?",
    "Have you ever had to present in front of a group? How did it go?",
    "Tell me about a time you worked with a diverse group of people.",
    "Describe a situation where you had to be detail-oriented.",
    "Tell me about a time you made a suggestion that was implemented.",
    "Can you share an experience where you had to show leadership?",
    "Describe a situation where you had to deal with ambiguity.",
    "Tell me about a time you were responsible for achieving a specific result.",
    "Can you give an example of when you had to stay focused under pressure?",
    "Have you ever had to negotiate? What was the result?",
    "Tell me about a time you set a goal and achieved it.",
    "Describe a situation where you were a mediator between conflicting parties.",
    "Tell me about a time you helped improve team dynamics.",
    "Can you share an example of when you were a good team player?",
    "Describe a situation where you had to be accountable for your actions.",
    "Tell me about a time you had to make a tough choice.",
    "Can you give an example of when you had to be flexible?",
    "Have you ever had to manage or train someone? How did you approach it?",
    "Tell me about a time you took responsibility for a mistake.",
    "Describe a situation where you had to show integrity.",
    "Tell me about a time you had to deliver results with little guidance.",
    "Can you share an experience when you had to manage time effectively?",
    "Describe a situation where you had to follow procedures.",
    "Tell me about a time you had to work extra hard to meet a goal.",
    "Can you give an example of when you had to handle a sudden change in priorities?",
    "Have you ever had to deal with an unsatisfied customer? What did you do?",
    "Tell me about a time you successfully met a customer's needs.",
    "Describe a situation where you were proactive.",
    "Tell me about a time you had to keep a positive attitude in a challenging situation.",
    "Can you share an example of when you met a long-term goal?",
    "Describe a situation where you had to analyze data or information to make a decision.",
    "Tell me about a time you contributed to a team project."
]

medium_behavioral_questions = [
    "Describe a time when you had to navigate through office politics to achieve a goal.",
    "Tell me about a situation where you had to work with someone who was difficult to get along with.",
    "Can you provide an example of a project where the scope changed midway? How did you handle it?",
    "Share an instance where you had to go above and beyond to get a job done.",
    "Tell me about a time when you had to build rapport with a client or colleague quickly.",
    "Describe a situation where you had to think on your feet because you lacked specific guidance.",
    "Tell me about a situation where you had to adapt your communication style to effectively interact with different people.",
    "How have you handled a situation where a team member was not contributing enough?",
    "Can you describe a time when you had to persuade a team to approach a problem in a new way?",
    "Share an instance when you had to rely on your analytical skills to move a project forward.",
    "Tell me about a situation where you had to gather input from others to make a decision.",
    "Describe a project that required you to work closely with departments outside of your own. How did you manage it?",
    "Tell me about a time when you had to deal with a significant setback in a project.",
    "Can you provide an example of a time when you had to prioritize one project or task over another?",
    "Share an experience where you had to demonstrate leadership skills under pressure.",
    "Tell me about a time when you had to confront someone over a professional issue. What was the outcome?",
    "Describe a situation where you had to be very detail-oriented in analyzing information.",
    "Share an instance where you had to handle multiple priorities and deadlines.",
    "Tell me about a time when you had to mentor or coach someone who was struggling.",
    "Describe a time when you had to resolve a conflict among team members.",
    "How have you handled a situation where you had to meet multiple objectives that seemed to conflict with each other?",
    "Tell me about a time when you needed to influence a group of people.",
    "Describe a challenging client you've dealt with. How did you handle the situation?",
    "Share an instance where you took a risk in the workplace. What was the outcome?",
    "Tell me about a time you had to be creative to solve a problem.",
    "Describe a time when you received constructive criticism and how you dealt with it.",
    "Tell me about a time when you had to handle an unexpected crisis at work.",
    "Can you provide an example of a time you were able to demonstrate excellent organizational skills?",
    "Share an experience when you had to rely heavily on your technical skills.",
    "Tell me about a time you successfully delegated tasks during a project.",
    "Describe a situation where you had to carefully choose your words when speaking with someone.",
    "Share an instance where you had to take immediate action in a challenging situation.",
    "Tell me about a time when you had to maintain a high standard of service in a difficult environment.",
    "How have you gone about making important decisions when key stakeholders had different opinions?",
    "Tell me about a situation where you had to maintain confidentiality.",
    "Describe a time when you needed to present complex information in a simplified way.",
    "Tell me about a project that required a long-term commitment. How did you keep your team motivated?",
    "Share an instance where you had to use data or metrics to support your argument.",
    "Tell me about a situation where you had to demonstrate ethical behavior.",
    "Describe a time when you had to sacrifice short-term objectives for long-term goals.",
    "Share an experience where you had to manage a difficult project with tight deadlines.",
    "Tell me about a time when you had to manage a team through a period of change.",
    "Describe a situation where you had to self-learn to accomplish a task.",
    "Share an instance where you had to be resilient in the face of obstacles.",
    "Tell me about a time you had to manage up.",
    "Describe a situation where you disagreed with a team member. How did you resolve it?",
    "Tell me about a project where you had to collaborate with other departments or teams.",
    "Share an experience where you had to make a crucial decision under time pressure.",
    "Describe a situation where you had to take accountability for a mistake.",
    "Tell me about a time when you successfully managed your team to achieve a goal.",
    "Share an instance where you had to adapt to a major change at work.",
    "Tell me about a time when you had to deal with ambiguity.",
    "Describe a time when you had to be particularly resourceful to get things done.",
    "Share an instance where you had to negotiate for the benefit of your team or project.",
    "Tell me about a situation where you had to consider the long-term implications of your decisions.",
    "Describe a time when you had to perform a task outside of your normal job responsibilities.",
    "Share an experience where you had to critically evaluate information to make a decision.",
    "Tell me about a time when you had to manage conflicting priorities.",
    "Describe a situation where you had to work with a wide range of personalities.",
    "Share an instance where you had to manage stakeholder expectations.",
    "Tell me about a time you had to implement a change based on feedback.",
    "Describe a time when you had to come up with a strategy under challenging conditions.",
    "Share an experience where you led a team to achieve a difficult project or task.",
    "Tell me about a situation where you had to troubleshoot an issue.",
    "Describe a time when you had to take a difficult ethical stand at work.",
    "Share an instance where you had to repair a professional relationship.",
    "Tell me about a time when you had to develop a new process or procedure from scratch.",
    "Describe a situation where you had to be especially diplomatic.",
    "Share an instance where you faced a lot of stress at work and how you handled it.",
    "Tell me about a time when you had to lead a remote team or manage a remote project.",
    "Describe a time when you had to take on the role of mediator during a conflict.",
    "Share an experience where you had to deliver disappointing news to a team or client.",
    "Tell me about a situation where you had to display emotional intelligence.",
    "Describe a time when you had to overcome a significant obstacle on a project.",
    "Share an instance where you had to show resilience against external pressures.",
    "Tell me about a situation where you had to manage or participate in a globally dispersed team.",
    "Describe a time when you were able to turn around a negative customer experience."
]

hard_behavioral_questions = [
    "Describe a time when you had to intervene in a conflict between two high-level stakeholders. How did you handle it?",
    "Tell me about a situation where you had to manage a team through a major organizational change, like a merger or restructuring.",
    "Share an instance where you had to deal with a severe budget cut. How did you allocate resources?",
    "Can you provide an example of a project where you had to navigate complex regulations or red tape?",
    "Describe a situation where you had to confront ethical misconduct in the workplace.",
    "Tell me about a time when you had to manage a project with a team that was resistant to your leadership.",
    "Share an experience where you had to rescue a project that was failing. What specific steps did you take?",
    "How have you handled a situation where your direct reports were more experienced or skilled in certain areas than you were?",
    "Tell me about a time you had to terminate an employee. How did you approach the situation?",
    "Describe a situation where you had to manage a project with unclear or shifting objectives.",
    "Share an instance where you had to implement a solution that you knew would be unpopular. How did you manage the fallout?",
    "Tell me about a time when you had to balance short-term gains against long-term impacts. What guided your decisions?",
    "Can you provide an example where you had to navigate conflicting directives from upper management?",
    "Describe a situation where you had to prioritize one business unit’s needs over another. How did you handle it?",
    "Tell me about a time when you had to adapt your leadership style to meet the needs of a diverse team.",
    "Share an experience where you had to manage a remote or dispersed team across different time zones.",
    "How have you managed a situation where you had to enforce unpopular policies mandated by higher-ups?",
    "Tell me about a project where you had to solve a problem without sufficient resources.",
    "Describe a situation where you had to manage a team through a failure. How did you maintain team morale?",
    "Share an instance when you had to challenge an organizational decision or policy. What was the outcome?",
    "How have you dealt with a situation where you had to lead a team that was not meeting performance expectations?",
    "Tell me about a time when you had to manage competing interests among your team members.",
    "Can you provide an example of a time you had to persuade or gain buy-in from a skeptical executive or board member?",
    "Describe a situation where you had to adapt your project to cope with rapid industry changes.",
    "Share an experience where you had to make a strategic pivot. How did you handle it?",
    "How have you handled a situation where you had to make a crucial decision but had conflicting data or opinions?",
    "Tell me about a time when you had to navigate a highly political organizational landscape.",
    "Describe a situation where you had to operate in an environment with conflicting stakeholder agendas.",
    "Share an instance where you had to manage an underperforming but highly talented individual.",
    "Tell me about a time when you had to work on a mission-critical project with a tight deadline.",
    "How have you managed projects with teams from diverse cultural, professional, or disciplinary backgrounds?",
    "Tell me about a time when you had to use diplomatic skills to defuse a volatile situation.",
    "Can you provide an example where you had to manage internal competition among team members?",
    "Describe a situation where you had to tackle a challenge that was outside of your expertise.",
    "Share an experience where you had to manage a crisis that threatened the reputation of your organization.",
    "How have you managed to innovate within a strict or conservative company culture?",
    "Tell me about a time you had to resolve a high-stakes conflict with a client or business partner.",
    "Describe a situation where you were faced with a high-stress project with high financial stakes.",
    "Share an instance where you had to champion diversity and inclusion in a resistant environment.",
    "Tell me about a time when you had to anticipate future business or industry trends and take action.",
    "How have you handled a situation where you were managing a team but did not have hiring or firing authority?",
    "Tell me about a time you had to salvage a business relationship that was seriously damaged.",
    "Describe a situation where you had to scale up a project rapidly.",
    "Share an experience where you led a multidisciplinary project involving complex technical requirements.",
    "How have you handled a situation where you were faced with diminishing market share or increased competition?",
    "Tell me about a time when you had to manage complex negotiations involving multiple stakeholders.",
    "Describe a situation where you had to assess and act upon risks that were difficult to quantify.",
    "Share an instance where you had to adapt an existing project to meet new compliance or legal standards.",
    "How have you managed the transition of a project or team from a traditional model to an agile or remote model?",
    "Tell me about a situation where you had to use a combination of data analytics and gut feeling to make a decision.",
    "Describe a situation where you were responsible for implementing a project that significantly altered business processes.",
    "Share an experience where you had to motivate a team facing a prolonged period of uncertainty."
]

easy_situational_questions = [
    "How would you handle a customer who is unhappy with a product?",
    "What would you do if you disagreed with a team member's approach to a project?",
    "How would you approach completing multiple tasks with the same deadline?",
    "What would you do if you made a mistake that no one else noticed?",
    "How would you handle a disagreement with a manager?",
    "What would you do if a teammate was not contributing to a group project?",
    "How would you handle a situation where you're assigned a task outside of your job description?",
    "What would you do if you were running late on a project deadline?",
    "How would you approach a difficult conversation with a colleague?",
    "What steps would you take if you were assigned to work with a difficult client?",
    "How would you handle receiving constructive criticism?",
    "What would you do if a team member was resistant to a new company policy?",
    "How would you approach a task you've never done before?",
    "What would you do if you had a conflict with a remote colleague?",
    "How would you handle it if you felt overwhelmed with your workload?",
    "What would you do if you noticed a mistake in a report that had already been sent out?",
    "How would you approach delegating tasks for a group project?",
    "What would you do if you were struggling to meet a performance expectation?",
    "How would you handle a situation where a customer is asking for something against company policy?",
    "What steps would you take if you were not satisfied with the quality of a teammate's work?",
    "How would you manage work if you had to report to multiple managers?",
    "What would you do if a project didn't turn out as well as you had hoped?",
    "How would you handle a situation where you have to work closely with a colleague you don't get along with?",
    "What would you do if you were asked to perform a task you don't agree with?",
    "How would you approach learning a new software required for your job?",
    "What would you do if you were faced with an ethical dilemma at work?",
    "How would you handle a situation where you're asked to compromise on the quality of a project due to time constraints?",
    "What would you do if a coworker took credit for your work?",
    "How would you handle a customer who is asking for a discount?",
    "What would you do if you were tasked with a project that didn't align with your career goals?",
    "How would you manage your time if you had both short-term and long-term projects to handle?",
    "What would you do if a client was unhappy with the speed of your work?",
    "How would you approach solving a problem you've never encountered before?",
    "What would you do if a team member consistently misses deadlines?",
    "How would you handle a situation where you have to give negative feedback to a colleague?",
    "What would you do if you felt a certain company process could be done more efficiently?",
    "How would you manage your tasks if you had to unexpectedly work from home?",
    "What would you do if you were given the opportunity to lead a project?",
    "How would you approach a situation where you have insufficient resources to complete a task?",
    "What would you do if you were asked to share your thoughts during a meeting and you weren't prepared?",
    "How would you handle a situation where your team's motivation is low?",
    "What would you do if you had to switch from individual work to teamwork suddenly?",
    "How would you handle a situation where you have a creative disagreement with a colleague?",
    "What would you do if you found out a colleague is spreading rumors about you?",
    "How would you approach a task that requires strict confidentiality?",
    "What would you do if you were given more responsibilities but no pay increase?",
    "How would you handle an urgent request from a client while working on another important project?",
    "What would you do if you disagree with the way your manager wants to solve a problem?",
    "How would you handle a situation where you're asked to perform tasks that were not initially in your job description?",
    "What would you do if you realized you were going to miss a deadline?",
    "How would you handle a situation where a project you're working on suddenly has its budget cut?",
    "What would you do if you were assigned a project with a team member you've had conflicts with?",
    "How would you handle a situation where you're not getting along with a coworker?",
    "What would you do if your manager gave you feedback you disagree with?",
    "How would you handle a situation where you're asked to work on a weekend?",
    "What would you do if you were asked to help onboard a new team member?",
    "How would you handle a situation where you're asked to work on a project you're not passionate about?",
    "What would you do if you're not feeling challenged in your current role?",
    "How would you handle a situation where you're expected to perform tasks in a very short timeframe?",
    "What would you do if a customer complains about a colleague?",
    "How would you approach a colleague who's not pulling their weight on a team project?",
    "What would you do if you found out a team member is violating company policy?",
    "How would you handle a situation where your boss asks you to do something that you think is not part of your role?",
    "What would you do if you're offered a promotion that you feel you're not ready for?",
    "How would you handle a situation where a project's scope changes midway?",
    "What would you do if you disagree with a corporate decision?",
    "How would you handle a situation where a team member leaves suddenly and you have to take over their responsibilities?",
    "What would you do if a colleague is constantly late to meetings?",
    "How would you handle a situation where your team is resistant to change?",
    "What would you do if you have to report a colleague for unethical behavior?",
    "How would you handle a situation where your initial solution to a problem didn't work?",
    "What would you do if you received unclear instructions for a project?",
    "How would you handle a situation where your team missed an important deadline?",
    "What would you do if a coworker asks you for help when you're busy with your own tasks?",
    "How would you handle a situation where you're asked to compromise your values for your job?",
    "What would you do if a key stakeholder is unsatisfied with your project?",
    "How would you handle a situation where you're asked to represent your team in front of executives?",
    "What would you do if you're assigned a high-priority project at the last minute?",
    "How would you handle a situation where your manager gives you conflicting tasks?",
    "What would you do if a coworker confronts you about a mistake they think you made?",
    "How would you handle a situation where you're asked to take on a leadership role temporarily?",
    "What would you do if you're experiencing a lack of communication from your team?",
    "How would you handle a situation where you need to meet tight deadlines for multiple projects?",
    "What would you do if you were assigned a project with no clear guidelines?",
    "How would you handle a situation where you're asked to join a meeting without any preparation?",
    "What would you do if your manager is absent and you're faced with a problem you're unsure how to solve?",
    "How would you handle a situation where you're asked to multitask excessively?",
    "What would you do if you were assigned a task that you feel is below your skill level?",
    "How would you handle a situation where a colleague does not respect your personal space?",
    "What would you do if you feel that you're not being adequately compensated for your work?"
]

medium_situational_questions = [
    "How would you handle a situation where a high-profile project failed due to your oversight?",
    "What would you do if you discover a colleague is bypassing important safety protocols?",
    "How would you handle a situation where you find out a team member is actively undermining the project?",
    "What would you do if your direct reports feel your manager treats them unfairly?",
    "How would you handle it if you were asked to finish a project much sooner than initially planned?",
    "What would you do if you had to manage someone who is older and has more experience than you?",
    "How would you approach a situation where you're assigned to work on a project that's outside of your expertise?",
    "What would you do if you had to manage a highly talented but unmotivated team member?",
    "How would you handle a situation where your team doesn't believe in the project's viability?",
    "What would you do if you were suddenly assigned to manage a remote team?",
    "How would you approach a situation where you are to lead a project with little to no budget?",
    "What would you do if a colleague was monopolizing all the resources for a project?",
    "How would you handle a situation where a team member is great at their job but toxic to the team environment?",
    "What would you do if a subordinate challenged your decision in a public meeting?",
    "How would you handle a situation where you realize you have taken on too many commitments?",
    "What would you do if the company suddenly pivoted its strategy, rendering your current project irrelevant?",
    "How would you approach communicating layoffs to your team?",
    "What would you do if you found out that your manager was sharing confidential information?",
    "How would you handle a situation where a customer threatens to leave a poor review if they don't get an unwarranted discount?",
    "What would you do if your manager gave you an unrealistic deadline?",
    "How would you approach a situation where a client wants features that weren’t initially agreed upon?",
    "What would you do if your closest teammate requested frequent time off during a critical project?",
    "How would you handle a situation where you are promoted but your former peers are unhappy about it?",
    "What would you do if a project requires expertise that your team doesn't possess?",
    "How would you handle it if your team's project did not meet the client's expectations?",
    "What would you do if you're in the middle of a presentation and your technology fails?",
    "How would you handle a situation where your direct report consistently underperforms?",
    "What would you do if a team member refuses to accept changes in a project?",
    "How would you handle it if an important stakeholder is not satisfied with your project's progress?",
    "What would you do if you have to negotiate a deadline with multiple departments?",
    "How would you handle a situation where your team members are not adapting well to new technologies?",
    "What would you do if you realize that a client's request would go against your ethical standards?",
    "How would you approach a situation where your project receives unexpected negative publicity?",
    "What would you do if a client is clearly wrong but insists they are right?",
    "How would you handle it if you're asked to supervise friends or family?",
    "What would you do if a key team member suddenly resigned in the middle of a project?",
    "How would you approach a situation where a project's failure could significantly impact the company?",
    "What would you do if your team is reluctant to adopt new procedures or processes?",
    "How would you handle a situation where your subordinates are not meeting their performance metrics?",
    "What would you do if you were asked to take the lead on a project for which you have no training?",
    "How would you handle it if you were required to enforce a policy you didn't agree with?",
    "What would you do if you discover a way to significantly cut costs but it would lead to layoffs?",
    "How would you approach a situation where a project has unclear or shifting objectives?",
    "What would you do if you found out another department is working on a very similar project?",
    "How would you handle a situation where the executive team requests frequent updates that interfere with your work?",
    "What would you do if you're tasked with managing a project you think is doomed to fail?",
    "How would you handle it if your direct report lied about completing a task?",
    "What would you do if a new hire is not as skilled as they claimed during the interview?",
    "How would you approach a situation where a customer wants a refund that violates company policy?",
    "What would you do if you had to work closely with a person who has political or religious beliefs that you strongly disagree with?",
    "How would you handle a situation where you are given a leadership position without adequate authority?",
    "What would you do if your team is not on board with the company’s mission?",
    "How would you approach a situation where your project is at risk due to frequent changes in client requirements?",
    "What would you do if a coworker constantly interrupts you during meetings?",
    "How would you handle a situation where your project team is spread across different time zones?",
    "What would you do if your team's performance is affecting another department negatively?",
    "How would you approach getting stakeholder buy-in for a project that doesn't show immediate ROI?",
    "What would you do if team morale was low due to salary cuts?",
    "How would you handle it if a coworker is making false claims about your work?",
    "What would you do if you were unable to attend an important meeting last minute?",
    "How would you approach a situation where you need to collaborate with a difficult external partner?",
    "What would you do if you were assigned a task that conflicts with your personal values?",
    "How would you handle a situation where there's a conflict of interest with a supplier or client?",
    "What would you do if your project was cancelled halfway?",
    "How would you approach a situation where you have to replace a key team member midway through a project?",
    "What would you do if a team member consistently questions your authority?",
    "How would you handle it if a project stakeholder asks for special treatment?",
    "What would you do if you discovered a significant error in a project that's already halfway through?",
    "How would you approach a situation where your manager is too hands-off?",
    "What would you do if you had to work on multiple high-priority projects at the same time?",
    "How would you handle a situation where your project's success relies on another team that’s lagging behind?",
    "What would you do if a junior team member proposes an idea that's actually better than yours?",
    "How would you approach a situation where you have to reject a team member’s proposal?",
    "What would you do if the team is relying on a key decision from you, but you have insufficient information?",
    "How would you handle a situation where your team lacks the skill set to meet project requirements?",
    "What would you do if a client is satisfied but your team thinks they could have done a better job?",
    "How would you approach a situation where the team has to work overtime for a prolonged period?",
    "What would you do if your manager constantly changes his or her requirements?",
    "How would you handle it if a team member seems to be dealing with personal issues that affect their work?",
    "What would you do if you received contradictory feedback from multiple managers?",
    "How would you approach a situation where your project is running behind schedule and over budget?",
    "What would you do if a high-performing employee suddenly starts to underperform?",
    "How would you handle a situation where a client continually adds new features but refuses to extend deadlines?",
    "What would you do if your manager is not supportive of career development opportunities?",
    "How would you approach a situation where there's a lack of clarity in roles and responsibilities within the team?",
    "What would you do if someone from senior management takes credit for your work?",
    "How would you handle a situation where you are asked to share bad news with the team?",
    "What would you do if a team member wants to bypass standard procedures for the sake of speed?",
    "How would you approach a situation where the team questions your decisions due to a recent project failure?",
    "What would you do if you notice that a project is not going to meet its objectives unless significant changes are made?",
    "How would you handle it if you feel you're not getting the resources required to meet your objectives?",
    "What would you do if your team is not committed to continuous improvement?"
]

hard_situational_questions = [
    "How would you handle being told to implement a decision that you strongly disagree with?",
    "What would you do if you discovered serious misconduct by a C-suite executive in the company?",
    "How would you approach a situation where your team's work conflicts with another team’s objectives, putting company goals at risk?",
    "What would you do if you had to restructure your department due to budget cuts, knowing that layoffs are inevitable?",
    "How would you handle a whistleblowing situation within your team?",
    "What would you do if your team is resistant to a new company-wide policy that you know is crucial for survival?",
    "How would you deal with a situation where your team is deeply divided over a controversial company initiative?",
    "What would you do if you had to take a project in a direction that could potentially harm your personal reputation?",
    "How would you handle being asked to compromise on product quality to meet financial targets?",
    "What would you do if a client asks for something that would put the team at ethical risk?",
    "How would you handle a situation where the company faces a public scandal?",
    "What would you do if you found out that a project you’ve led for years was suddenly going to be outsourced?",
    "How would you approach having to shut down a high-performing but ethically problematic project?",
    "What would you do if your direct report accuses another executive of harassment?",
    "How would you handle a situation where you have to implement unpopular austerity measures?",
    "What would you do if you had to navigate a high-stakes merger or acquisition?",
    "How would you deal with discovering that there's a toxic but highly productive culture within a critical department?",
    "What would you do if a pivotal project faces failure just before launch?",
    "How would you handle an emergency situation that threatens the safety of your employees?",
    "What would you do if you were asked to manage a project that you think is doomed due to corporate politics?",
    "How would you approach a situation where you have to report directly to two conflicting bosses?",
    "What would you do if the government investigates your company for practices you’re responsible for?",
    "How would you deal with a situation where you have to fire a close friend?",
    "What would you do if you had to choose between losing your biggest client or compromising your company’s values?",
    "How would you handle a situation where you have to push your team far beyond their comfort zones?",
    "What would you do if a star employee starts to become complacent?",
    "How would you handle it if an employee threatens to quit unless they are given a promotion?",
    "What would you do if you had to promote one person from a group of equally deserving candidates?",
    "How would you deal with a situation where your company is at risk of bankruptcy?",
    "What would you do if a product failure caused harm to customers?",
    "How would you handle the ethical dilemma of profit vs. social responsibility?",
    "What would you do if you were responsible for a mistake that cost the company a significant amount of money?",
    "How would you approach being asked to create a diversity and inclusion policy in a resistant company culture?",
    "What would you do if your team wanted to proceed in a way that you found fundamentally flawed?",
    "How would you handle a situation where you’re asked to spy on a competitor?",
    "What would you do if one of your team members was showing signs of burnout but was crucial for project completion?",
    "How would you handle a situation where you're asked to turn around a failing division?",
    "What would you do if you were asked to step down from a leadership position?",
    "How would you approach a situation where an executive team member is intentionally setting you up for failure?",
    "What would you do if you had to manage a team across significantly different cultures?",
    "How would you deal with receiving negative feedback in a very public forum?",
    "What would you do if you’re tasked with enforcing an unethical company policy?",
    "How would you handle a situation where you need to drastically innovate in a highly regulated industry?",
    "What would you do if you were asked to take a significant pay cut?",
    "How would you deal with a direct report who performs well but is extremely disliked?",
    "What would you do if you were asked to relocate on short notice?",
    "How would you handle a situation where you’re faced with significant resistance from senior management?",
    "What would you do if your strategy is copied by a competitor?",
    "How would you deal with having to lay off employees knowing that it could tarnish your reputation as a leader?",
    "What would you do if you were asked to oversee a project that compromises your work-life balance?",
    "How would you handle an acquisition that would result in job loss for your team but long-term gains for the company?",
    "What would you do if a colleague sabotaged a project you are responsible for?",
    "How would you handle multiple teams that all need your immediate attention and resources?",
    "What would you do if a direct report asked for your job?",
    "How would you deal with finding out you’re significantly underpaid compared to your peers?",
    "What would you do if a change in government regulation severely affected your project?",
    "How would you handle discovering that your team inflated their results?",
    "What would you do if your employees staged a walkout?",
    "How would you handle receiving a bad performance review?",
    "What would you do if you're asked to lead a team that has failed numerous projects?",
    "How would you deal with a high-performing team member who constantly pushes boundaries?",
    "What would you do if a colleague publicly criticized you?",
    "How would you handle suddenly losing your biggest client?",
    "What would you do if you found out a team member was interviewing elsewhere?",
    "How would you handle a situation where a product launch is delayed and it affects the stock price?",
    "What would you do if a team member accused you of favoritism?",
    "How would you handle a situation where you need to cancel a project that the team was excited about?",
    "What would you do if your manager engaged in unethical behavior?",
    "How would you approach a situation where you need to terminate a partnership that is personally beneficial but bad for the company?",
    "What would you do if you’re forced to make a decision without sufficient information?",
    "How would you handle being demoted?",
    "What would you do if a new technology threatened to make your role obsolete?",
    "How would you deal with office politics affecting your team's morale?",
    "What would you do if your actions were misinterpreted and led to a scandal?",
    "How would you handle being the new leader of a high-performing, tight-knit team?",
    "What would you do if your project’s success depended on a competitor's failure?",
    "How would you handle a situation where your team is underperforming and you can't figure out why?",
    "What would you do if an influential team member is purposefully withholding information?",
    "How would you deal with a team that's lost trust in your leadership?",
    "What would you do if you were asked to work on a project that goes against your moral values?",
    "How would you handle a situation where your team becomes too dependent on you?",
    "What would you do if your most trusted team member betrayed you?",
    "How would you deal with a situation where your project has a high chance of failure but high rewards?",
    "What would you do if your boss takes credit for your work in a board meeting?",
    "How would you handle a team that's become complacent after a long period of success?",
    "What would you do if your team is overwhelmed but you’re not allowed to hire more people?",
    "How would you approach a situation where you’ve lost the confidence of your superiors?",
    "What would you do if you were offered a lucrative job at a competing company?",
    "How would you deal with a crisis situation where you need to choose between employee well-being and company survival?",
    "What would you do if you had to publicly admit to a failure that wasn't your fault?",
    "How would you handle a situation where you have to choose between cutting salaries or losing employees?",
    "What would you do if you found out your team was keeping secrets from you?",
    "How would you handle it if you were asked to implement a strategy you knew had failed at another company?",
    "What would you do if your closest colleague turned out to be undermining you?",
    "How would you approach a situation where you are asked to lead a team on a project for which you have no expertise?",
    "What would you do if your project was suddenly deprioritized in favor of another project?",
    "How would you handle a situation where you’re asked to compromise on the quality of a project to meet a tight deadline?",
    "What would you do if you're asked to cut corners on a project to meet investor expectations?",
    "How would you handle a situation where a decision could either result in a massive breakthrough or a significant setback?",
    "What would you do if your team refuses to adopt new technology that you believe is critical?"
]

easy_personal_questions = [
    "What are your hobbies?",
    "How do you like to spend your weekends?",
    "What is your favorite book and why?",
    "Do you prefer teamwork or working alone?",
    "What motivates you?",
    "What is your favorite movie?",
    "How do you handle stress?",
    "What are you passionate about?",
    "What's your favorite type of music?",
    "Do you have any favorite sports or physical activities?",
    "What does work-life balance mean to you?",
    "Do you prefer a structured environment or a more flexible work setting?",
    "What are your long-term career goals?",
    "What is your favorite subject and why?",
    "What's the last thing you learned that excited you?",
    "How do you prioritize your tasks?",
    "What is your favorite type of cuisine?",
    "Do you enjoy traveling? If so, what’s your favorite destination?",
    "How do you define success?",
    "What was the last project you led and what was its outcome?",
    "Do you consider yourself introverted or extraverted?",
    "How do you usually start your day?",
    "Do you have any mentors or people you look up to?",
    "What's your ideal vacation?",
    "How do you handle criticism?",
    "Are you more of a detail-oriented or big-picture person?",
    "What are you currently reading?",
    "How do you handle deadlines?",
    "What’s your go-to productivity trick?",
    "How do you prefer to receive feedback?",
    "What are some of your values?",
    "What's your favorite way to give back to the community?",
    "Do you have a favorite quote or mantra?",
    "How do you adapt to new situations?",
    "How would your friends describe you?",
    "What's your favorite season and why?",
    "What is something you're currently trying to improve on?",
    "Do you prefer city living or country living?",
    "What is your favorite type of art?",
    "How do you relax after a hard day of work?",
    "What do you think are your greatest strengths?",
    "Do you have any pets?",
    "What's your favorite holiday?",
    "How do you handle disagreements?",
    "What are some of your short-term goals?",
    "How do you feel about remote work?",
    "What's your favorite way to exercise?",
    "How do you like to celebrate your achievements?",
    "Do you enjoy cooking? If so, what’s your signature dish?",
    "What’s something you could talk about for hours?",
    "How would you spend a million dollars?",
    "What's your dream job?",
    "What are your favorite websites or apps?",
    "How do you handle conflict?",
    "What kind of work environment do you thrive in?",
    "Do you have any siblings?",
    "What's the most interesting place you've visited?",
    "What makes you happy?",
    "Do you have any favorite podcasts?",
    "What was your first job?",
    "How do you like to stay organized?",
    "What is your favorite board game?",
    "Do you have a morning routine?",
    "What's a skill you'd like to acquire?",
    "What’s a challenge you’ve overcome?",
    "How do you handle unexpected situations?",
    "What are some things on your bucket list?",
    "What's your favorite way to network?",
    "What are some of your leadership experiences?",
    "What's the most recent show you binge-watched and loved?",
    "Do you have any hidden talents?",
    "What's your favorite type of volunteer work?",
    "How do you set boundaries for yourself?",
    "What's your favorite way to unwind?",
    "What's a recent accomplishment you're proud of?",
    "Do you prefer coffee or tea?",
    "What are some of your favorite brands?",
    "Do you have a go-to comfort food?",
    "What's your favorite type of weather?",
    "What’s the most meaningful project you’ve worked on?",
    "Do you enjoy DIY projects?",
    "What's a cause you care deeply about?",
    "How do you like to be managed?",
    "What's your favorite outdoor activity?",
    "What’s a mistake you’ve learned from?",
    "How do you like to stay up-to-date with industry trends?",
    "Do you prefer handwritten notes or digital formats?",
    "What's your favorite childhood memory?",
    "Do you have any favorite YouTube channels?",
    "What are your thoughts on lifelong learning?",
    "How do you feel about public speaking?",
    "What’s a typical day like for you?",
    "How do you manage work-life balance?",
    "What’s your favorite local restaurant?"
]

easy_personal_questions = [
    "What are your hobbies?",
    "How do you like to spend your weekends?",
    "What is your favorite book and why?",
    "Do you prefer teamwork or working alone?",
    "What motivates you?",
    "What is your favorite movie?",
    "How do you handle stress?",
    "What are you passionate about?",
    "What's your favorite type of music?",
    "Do you have any favorite sports or physical activities?",
    "What does work-life balance mean to you?",
    "Do you prefer a structured environment or a more flexible work setting?",
    "What are your long-term career goals?",
    "What is your favorite subject and why?",
    "What's the last thing you learned that excited you?",
    "How do you prioritize your tasks?",
    "What is your favorite type of cuisine?",
    "Do you enjoy traveling? If so, what’s your favorite destination?",
    "How do you define success?",
    "What was the last project you led and what was its outcome?",
    "Do you consider yourself introverted or extraverted?",
    "How do you usually start your day?",
    "Do you have any mentors or people you look up to?",
    "What's your ideal vacation?",
    "How do you handle criticism?",
    "Are you more of a detail-oriented or big-picture person?",
    "What are you currently reading?",
    "How do you handle deadlines?",
    "What’s your go-to productivity trick?",
    "How do you prefer to receive feedback?",
    "What are some of your values?",
    "What's your favorite way to give back to the community?",
    "Do you have a favorite quote or mantra?",
    "How do you adapt to new situations?",
    "How would your friends describe you?",
    "What's your favorite season and why?",
    "What is something you're currently trying to improve on?",
    "Do you prefer city living or country living?",
    "What is your favorite type of art?",
    "How do you relax after a hard day of work?",
    "What do you think are your greatest strengths?",
    "Do you have any pets?",
    "What's your favorite holiday?",
    "How do you handle disagreements?",
    "What are some of your short-term goals?",
    "How do you feel about remote work?",
    "What's your favorite way to exercise?",
    "How do you like to celebrate your achievements?",
    "Do you enjoy cooking? If so, what’s your signature dish?",
    "What’s something you could talk about for hours?",
    "How would you spend a million dollars?",
    "What's your dream job?",
    "What are your favorite websites or apps?",
    "How do you handle conflict?",
    "What kind of work environment do you thrive in?",
    "Do you have any siblings?",
    "What's the most interesting place you've visited?",
    "What makes you happy?",
    "Do you have any favorite podcasts?",
    "What was your first job?",
    "How do you like to stay organized?",
    "What is your favorite board game?",
    "Do you have a morning routine?",
    "What's a skill you'd like to acquire?",
    "What’s a challenge you’ve overcome?",
    "How do you handle unexpected situations?",
    "What are some things on your bucket list?",
    "What's your favorite way to network?",
    "What are some of your leadership experiences?",
    "What's the most recent show you binge-watched and loved?",
    "Do you have any hidden talents?",
    "What's your favorite type of volunteer work?",
    "How do you set boundaries for yourself?",
    "What's your favorite way to unwind?",
    "What's a recent accomplishment you're proud of?",
    "Do you prefer coffee or tea?",
    "What are some of your favorite brands?",
    "Do you have a go-to comfort food?",
    "What's your favorite type of weather?",
    "What’s the most meaningful project you’ve worked on?",
    "Do you enjoy DIY projects?",
    "What's a cause you care deeply about?",
    "How do you like to be managed?",
    "What's your favorite outdoor activity?",
    "What’s a mistake you’ve learned from?",
    "How do you like to stay up-to-date with industry trends?",
    "Do you prefer handwritten notes or digital formats?",
    "What's your favorite childhood memory?",
    "Do you have any favorite YouTube channels?",
    "What are your thoughts on lifelong learning?",
    "How do you feel about public speaking?",
    "What’s a typical day like for you?",
    "How do you manage work-life balance?",
    "What’s your favorite local restaurant?"
]

medium_personal_questions = [
    "What book has had the most impact on your life?",
    "How do you handle ethical dilemmas in your life?",
    "What’s the most challenging project you've ever undertaken and how did you handle it?",
    "How do you balance ambition with contentment?",
    "What’s a significant change you’ve made in your life and why?",
    "How do you navigate work-life balance when under extreme pressure?",
    "What’s your philosophy on teamwork?",
    "Describe a time when your values were tested and how you handled it.",
    "What makes a workplace feel like a great fit for you?",
    "What are you doing to develop yourself personally and professionally?",
    "How do you manage personal biases when making decisions?",
    "What are your methods for staying resilient in challenging situations?",
    "How would you handle a personal conflict with a coworker?",
    "What's a controversial opinion you hold?",
    "What aspects of your personality are you working to improve?",
    "How do you keep up with current events, and why do you think it's important?",
    "What are the most crucial factors that contribute to your happiness?",
    "What principles guide your life and work?",
    "How do you approach giving and receiving feedback?",
    "What’s something you’ve learned about yourself as you’ve gotten older?",
    "How do you handle fear of failure?",
    "How important is it for you to have a social impact with your work?",
    "How do you deal with work-related stress?",
    "What’s a leadership challenge you've faced and how did you resolve it?",
    "How do you prioritize your mental health?",
    "What's a non-materialistic goal you have?",
    "How do you set boundaries in your professional life?",
    "What are some habits you are currently trying to build or break?",
    "How do you handle emotional labor in the workplace?",
    "How do you manage self-doubt?",
    "Describe your thought process for making difficult decisions.",
    "What’s an unpopular work-related opinion you have?",
    "How do you approach risk-taking?",
    "How have your past experiences shaped your values?",
    "What are your methods for self-reflection?",
    "How do you handle disagreements in a team setting?",
    "What are the qualities you admire most in a leader?",
    "How do you approach time management?",
    "What are your thoughts on the work-hard-play-hard culture?",
    "What steps do you take to continue learning and growing?",
    "How do you deal with negative feedback?",
    "What’s a recent trend that you find troubling?",
    "How do you adapt to shifting priorities or objectives?",
    "How do you ensure inclusivity in your professional interactions?",
    "What do you value more: process or outcome?",
    "How do you keep yourself motivated during repetitive tasks?",
    "How do you evaluate success in your life?",
    "What’s a challenge you foresee in your future career?",
    "How do you foster a culture of respect and integrity?",
    "What's the importance of self-awareness in your life?",
    "How do you ensure you’re continuously pushing yourself outside of your comfort zone?",
    "How do you prioritize when you have conflicting responsibilities?",
    "What role does empathy play in your life?",
    "What are your thoughts on mentorship?",
    "How do you navigate personal vs. professional relationships at work?",
    "What’s the most impactful criticism you’ve received?",
    "How do you build trust within a team?",
    "What role does failure play in your life?",
    "How do you cultivate a sense of purpose in your work?",
    "What strategies do you employ for effective communication?",
    "How do you manage your energy levels throughout the day?",
    "What’s your strategy for maintaining focus in a world full of distractions?",
    "How important is cultural fit to you when choosing a place to work?",
    "How do you deal with ambiguity in decision-making?",
    "How do you ensure that you maintain a balanced perspective?",
    "How do you handle personal conflicts in a professional setting?",
    "What role do ethics play in your personal and professional life?",
    "How do you find meaning in mundane tasks?",
    "What’s the most complex problem you’ve solved?",
    "How do you approach the concept of work-life integration?",
    "What’s the most courageous thing you’ve done?",
    "How do you deal with competing priorities or objectives?",
    "What are your thoughts on lifelong commitments and responsibilities?",
    "What's your philosophy on personal development?",
    "What’s a personal flaw you’ve turned into an asset?",
    "How do you handle disappointment?",
    "How do you maintain integrity in difficult situations?",
    "What's your strategy for decision-making?",
    "How do you deal with imposter syndrome?",
    "How do you maintain work-life boundaries while working remotely?",
    "How do you keep yourself accountable?",
    "How do you manage the balance between humility and self-promotion?",
    "How do you handle the tension between ethics and business goals?",
    "What is your philosophy on building relationships?",
    "What role does gratitude play in your life?",
    "How do you adapt to rapidly changing work environments?",
    "What are your strategies for conflict resolution?",
    "What role does authenticity play in your life?",
    "What are your coping mechanisms for dealing with setbacks?",
    "How do you approach the balance between idealism and pragmatism?",
    "What role does family play in your life and career?",
    "How do you maintain your skill set with changing industry standards?",
    "How do you approach learning from your mistakes?",
    "What are your expectations from a job aside from salary?",
    "How do you maintain focus over extended periods?",
    "What are the key elements that make up your identity?",
    "How do you evaluate opportunities in your life?",
    "How do you ensure you’re aligned with your core values in your daily actions?"
]

hard_personal_questions = [
    "What’s a belief you held strongly but changed your mind about? Why?",
    "Describe a time you had to sacrifice your personal values for your job. How did you handle it?",
    "How do you reconcile your own biases when making important decisions?",
    "What’s the most difficult ethical decision you’ve had to make?",
    "What are your thoughts on the concept of work as a calling versus work as a job?",
    "How do you respond when your personal values conflict with those of your employer?",
    "Can you provide an example of when you had to navigate office politics?",
    "What do you consider to be your ethical responsibilities to yourself and others?",
    "How do you handle situations where your integrity is questioned?",
    "How would you respond if you discovered a colleague was doing something unethical?",
    "What’s the most morally complex situation you’ve ever faced?",
    "How do you resolve conflicts between your personal and professional life?",
    "Describe a situation where you had to stand up for your convictions, despite backlash.",
    "What are the implications of 'cancel culture' in today’s society?",
    "How do you approach morally grey areas in your personal or professional life?",
    "Can you describe an instance when you had to admit you were wrong? How did you handle it?",
    "How do you manage situations where there’s a disparity between your values and societal norms?",
    "What are your thoughts on the concept of ‘radical honesty’?",
    "How do you deal with ethical implications in ambiguous situations?",
    "How do you maintain integrity when no one is watching?",
    "What is your philosophy on social justice?",
    "How do you approach work-life balance in a culture of endless productivity?",
    "How do you prioritize your own well-being when faced with professional pressures?",
    "What role does privilege play in your personal and professional life?",
    "How do you challenge your own perspectives and prejudices?",
    "What’s your perspective on the ethical use of power in a leadership role?",
    "How do you navigate political discussions in the workplace?",
    "What is your stance on social issues in the workplace?",
    "How would you handle discovering that your work indirectly supports an unethical industry?",
    "How do you foster ethical behavior in a team?",
    "What are your views on equality versus equity?",
    "How do you reconcile your career ambitions with social responsibilities?",
    "How do you respond when your ethical beliefs are in the minority?",
    "How do you approach the concept of ‘duty’ in your personal and professional life?",
    "What are your thoughts on activism in the workplace?",
    "How do you make choices in situations where ethical and legal boundaries collide?",
    "What would you do if you were asked to compromise your ethical standards by your employer?",
    "How do you navigate professional settings where you feel your values aren't respected?",
    "How do you ensure you’re not contributing to a toxic work culture?",
    "What are your thoughts on the ethical implications of AI and machine learning?",
    "How do you negotiate personal freedom with societal responsibilities?",
    "What are the limits of loyalty in a professional context?",
    "How do you reconcile personal ambition with ethical considerations?",
    "What is your approach to balancing self-interest and altruism?",
    "How would you handle a situation where your actions could benefit you but negatively impact others?",
    "What are your thoughts on the ‘ends justify the means’?",
    "What role do ethics play in your consumption habits?",
    "How do you maintain your principles in an environment that doesn’t support them?",
    "What is your stance on the ethical dilemmas surrounding data privacy?",
    "How do you approach issues of inequality in your personal and professional life?",
    "What would you do if you were aware of a significant ethical violation but speaking out would jeopardize your job?",
    "What is your philosophy on personal responsibility?",
    "How do you approach conversations about social issues that can be polarizing?",
    "What is your definition of moral courage?",
    "How do you handle your own ethical shortcomings?",
    "How do you weigh societal norms against your own values in decision-making?",
    "How do you approach accountability in situations where it could have adverse effects on your career?",
    "What would you do if your work conflicted with a cause you deeply care about?",
    "How do you address your own limitations in achieving ethical or moral standards?",
    "How do you manage moral relativism in a globalized world?",
    "How do you handle situations where there is a conflict between ethics and profit?",
    "How would you deal with a situation where taking a moral stand could isolate you socially or professionally?",
    "How do you navigate the intersection of ethics and cultural differences?",
    "How do you approach ethical dilemmas where there is no clear right or wrong?",
    "What would you do if your values were in direct conflict with your career goals?",
    "What’s your approach to ethical considerations in a rapidly changing societal context?",
    "How do you maintain ethical standards in high-stress situations?",
    "How do you balance long-term ethical implications with short-term gains?",
    "What are the ethical considerations that you think are often overlooked in your field?",
    "What are your thoughts on the concept of ‘personal integrity’ in a digital age?",
    "How do you practice ethical behavior in a society that often rewards unethical actions?",
    "What is your perspective on the ethics of care versus the ethics of justice?",
    "What are your thoughts on moral obligations to future generations?",
    "How do you navigate ethical dilemmas that have personal ramifications?",
    "What are your thoughts on the responsibility of individuals versus systems in ethical behavior?",
    "How do you approach ethical dimensions of sustainability and environmental responsibility?",
    "What are your thoughts on the ethics of information and misinformation?",
    "How do you manage your own ethical conduct in a culture that may not always prioritize it?",
    "What’s your approach to ethical decision-making in a rapidly evolving industry?",
    "How do you uphold ethical considerations when they come at a personal cost?",
    "What role does moral philosophy play in your everyday decision-making?",
    "What’s your approach to handling situations where there is a gap between legal compliance and ethical responsibility?",
    "What are your thoughts on the ethics of global economic disparities?",
    "How do you handle situations where doing the ethical thing is not rewarded or even punished?",
    "How do you navigate moral dilemmas that arise from technological advancements?",
    "How do you maintain ethical rigor in a competitive environment?",
    "How do you balance ethical considerations with financial or practical constraints?",
    "How do you handle ethical challenges that are systemic in nature?",
    "What is your approach to ethical issues in an interdisciplinary context?",
    "What’s your perspective on the ethical considerations around human augmentation or modification?",
    "How do you reconcile ethical dilemmas that have both personal and professional implications?",
    "What’s your approach to ethical considerations in a post-truth era?",
    "How do you handle ethical considerations in contexts that are inherently subjective?"
]

easy_motivation_and_fit_questions = [
    "Why did you apply for this position?",
    "What interests you most about this job?",
    "What excites you about coming to work every day?",
    "Can you describe your ideal work environment?",
    "Why do you think you're a good fit for this company?",
    "What's your preferred management style?",
    "How do you like to receive feedback?",
    "What are you passionate about?",
    "What motivates you in your job?",
    "How do you handle stress or pressure?",
    "How do you prioritize your tasks?",
    "Can you describe a time you went above and beyond at work?",
    "What are your career goals?",
    "How do you approach teamwork?",
    "What can you bring to our team?",
    "How do you handle conflicts with team members?",
    "What is your approach to work-life balance?",
    "How do you adapt to new situations?",
    "What are you hoping to achieve in your next job?",
    "How do you continue learning and developing in your career?",
    "How do you stay motivated in a routine job?",
    "What attracts you to our company's culture?",
    "What do you like most about our products or services?",
    "How do you keep up-to-date with industry trends?",
    "What aspects of this job would make you look forward to coming to work?",
    "How do you align with our company values?",
    "What do you think are the most important qualities for someone in this role?",
    "How do you stay organized?",
    "Can you describe a time you took the initiative to improve something at work?",
    "How do you approach problem-solving?",
    "What’s the most rewarding project you’ve worked on?",
    "What are you looking for in a job?",
    "What would your ideal project look like?",
    "What’s your approach to handling criticism?",
    "How do you make decisions?",
    "What would make you stay at a company long-term?",
    "Can you describe a time you had to adapt to change?",
    "How do you approach deadlines?",
    "What are your hobbies outside of work?",
    "What would make you excited to work here?",
    "What are your salary expectations?",
    "How would you describe your work ethic?",
    "What kind of tasks do you enjoy the most?",
    "What kind of tasks do you find the most challenging?",
    "What is your ideal team size?",
    "How do you handle failure?",
    "What are your thoughts on remote work?",
    "What’s your favorite part about your current job?",
    "What's the most challenging part of your current job?",
    "How do you ensure you get along with team members?",
    "How do you keep track of your daily tasks and responsibilities?",
    "What is your approach to professional development?",
    "How would you describe your learning style?",
    "What's the first thing you would do if you were hired for this position?",
    "What has been your favorite job and why?",
    "What would a successful year in this role look like to you?",
    "How do you know when you’re doing a good job?",
    "What role do you usually take in a team?",
    "How do you approach time management?",
    "Do you prefer to work alone or as part of a team?",
    "How would you handle a difficult team member?",
    "What does your ideal Monday morning look like?",
    "How do you manage your energy throughout the day?",
    "How do you evaluate success?",
    "What attracts you to this industry?",
    "How would you feel about working overtime?",
    "What’s the most meaningful compliment you’ve received at work?",
    "How do you approach on-the-job learning?",
    "How do you handle constructive criticism?",
    "How would you contribute to our team dynamic?",
    "What are you currently learning or looking to learn?",
    "How do you ensure you meet deadlines?",
    "What qualities do you think make a great leader?",
    "How do you like to be managed?",
    "How do you balance attention to detail with meeting deadlines?",
    "Do you have any professional role models?",
    "What’s the most important feedback you’ve received?",
    "What’s the best team you’ve been a part of and why?",
    "How do you approach new challenges?",
    "What’s the most difficult task you’ve successfully completed?",
    "How do you keep a positive attitude at work?",
    "What are your professional strengths?",
    "What are areas you're working to improve professionally?",
    "How do you feel about taking on tasks outside your job description?",
    "What drew you to this industry originally?",
    "How do you maintain a work-life balance?",
    "What’s the most valuable lesson you’ve learned in your career so far?",
    "How do you handle tight deadlines?",
    "What's your favorite way to unwind after a busy day?",
    "How do you handle feedback?",
    "What would you do if you disagreed with your manager’s decision?",
    "What are the three most important factors for you in a job?"
]

medium_motivation_and_fit_questions = [
    "How do you align your personal goals with your work objectives?",
    "Can you discuss a time when your motivation was tested? How did you handle it?",
    "How would you feel about occasionally taking on tasks that are outside of your job description?",
    "What kinds of corporate cultures do you find the most fulfilling and why?",
    "Describe how you've contributed to the company culture in your previous roles.",
    "Can you discuss a time when you had to align a team towards a vision or goal?",
    "How do you feel about continuous learning and development in your career?",
    "What methods do you use to engage with a team that has a different work culture?",
    "How do you ensure that you fit well with a team, especially a diverse one?",
    "How would you deal with a team member who is hindering the team’s success?",
    "How do you ensure you're continually motivated in a job?",
    "How do you handle situations where you disagree with senior management?",
    "What's your philosophy on work-life balance, and how do you maintain it?",
    "Describe a professional failure you've had and what you learned from it.",
    "What strategies do you use to maintain a high level of motivation for mundane tasks?",
    "Can you discuss your experiences with cross-functional teams?",
    "How do you approach making a significant decision without complete information?",
    "How have you handled ethical dilemmas in your career?",
    "What role does your larger life purpose play in your career?",
    "How do you approach professional development and career growth?",
    "How do you prioritize when you have conflicting deadlines?",
    "How do you handle a team member who is not contributing equally?",
    "Discuss a time when you questioned the status quo at work. What was the outcome?",
    "How do you define success in your career?",
    "What would you do if you found out a team member was undermining team efforts?",
    "How do you align your team's goals with broader company objectives?",
    "Describe a situation where you had to motivate a demotivated team.",
    "What is your approach to handling workplace politics?",
    "How do you keep current with industry trends and how do they impact your role?",
    "What is your strategy for handling burnout?",
    "How do you foster diversity and inclusion within your team?",
    "How do you handle disagreements with coworkers?",
    "What are the key elements that make a team successful, in your opinion?",
    "What attracts you to a long-term tenure with a company?",
    "How do you balance ambition with job satisfaction?",
    "Describe a situation where you felt like giving up. How did you handle it?",
    "How would you react if a project you were passionate about was suddenly canceled?",
    "How do you deal with the monotony in repetitive tasks?",
    "How do you maintain focus and motivation during long projects?",
    "How do you manage your career goals with the roles you’ve taken?",
    "Describe a time when you chose to take a risk at work.",
    "How do you determine what’s the most important task to focus on?",
    "How do you stay motivated when you disagree with your manager’s decisions?",
    "What do you think your past supervisors would say about your contribution to work culture?",
    "What initiatives have you taken in your previous roles to improve team performance?",
    "How do you define professional success?",
    "What methods do you use to ensure you're aligned with your company's goals?",
    "How do you continue to motivate yourself and others in high-pressure situations?",
    "Describe a situation where you went beyond your job role to contribute to the company’s success.",
    "How would you balance team harmony with the need for performance?",
    "Describe a time when you felt your motivation dip. How did you recover?",
    "What strategies do you employ to remain focused on a project?",
    "How have you encouraged your team to align with company culture?",
    "Discuss a situation where you had to make a decision that was not popular. How did you handle it?",
    "How would you handle the situation if you felt a team member was culturally misaligned?",
    "What would you do if a personal issue affects your job performance?",
    "What are the attributes of a company that would make you excited to work there?",
    "How do you gauge your own success in a role?",
    "How do you foster motivation within a team you’re leading?",
    "Describe a time when you had to collaborate with a difficult colleague.",
    "How do you handle ambiguity in the workplace?",
    "What strategies do you employ to meet tight deadlines?",
    "Describe how you’ve adapted to a significant change at work.",
    "How do you motivate yourself when you're not interested in a task?",
    "How do you handle work environments that don't match your preferences?",
    "How do you maintain a sense of culture in remote or hybrid work settings?",
    "How do you prioritize tasks when you’re feeling overwhelmed?",
    "What steps do you take to ensure you’re aligned with a new company’s culture?",
    "Describe a situation where your work was criticized. How did you handle it?",
    "How do you approach work-life balance in high-stress roles?",
    "What is your strategy for maintaining job satisfaction over the long term?",
    "How do you respond to unexpected obstacles or challenges?",
    "What are your strategies for aligning with a new team quickly?",
    "Describe a time when you significantly contributed to improving team dynamics.",
    "How do you approach solving conflicts within a team?",
    "How would you handle feeling disengaged from your work?",
    "What actions have you taken to foster a healthy team culture?",
    "How do you approach setting and achieving your goals?",
    "How do you handle it when your personal beliefs conflict with those of your employer?",
    "What strategies do you employ to maintain work quality during stressful times?",
    "How do you maintain job satisfaction?",
    "Discuss a time when you had to adapt to a significant change in your industry or company.",
    "How do you approach working in a team vs. working independently?",
    "How would you handle a situation where you and your team are not aligned on a project?",
    "How do you approach maintaining a healthy work-life balance?",
    "Discuss a time when you took ownership of a project. What was the outcome?",
    "What strategies do you employ to balance teamwork and individual contribution?",
    "How do you maintain your motivation in a job where the tasks are similar?",
    "Describe how you've advocated for work-life balance in your previous roles."
]

hard_motivation_and_fit_questions = [
    "Describe a situation where your values clashed with the values of your team. How did you handle it?",
    "How would you approach a situation where you fundamentally disagree with the direction of the company?",
    "Discuss a time when you felt a company’s culture was counterproductive to its goals. What would you have changed?",
    "Can you give an example of how you've turned a team's culture around?",
    "Discuss an experience where you had to defend an unpopular decision that you knew was best for the organization.",
    "Describe a time you had to question an ethical decision made by your superiors. What did you do?",
    "What would you do if you were asked to perform tasks that contradict your personal ethics?",
    "Can you share an experience where you had to navigate significant cultural barriers to succeed in your role?",
    "Describe a situation where you took on a leadership role during a crisis. What were the outcomes?",
    "How have you managed a team that was resistant to change?",
    "Share a time when you had to manage your team through a significant setback or failure.",
    "What would you do if you were faced with a team that had completely different work ethics?",
    "How would you approach a situation where the majority of the team disagrees with your proposed strategy?",
    "Discuss an instance where you had to choose between career advancement and alignment with your values.",
    "Describe a situation where you sacrificed short-term success for the long-term benefit of the company.",
    "How would you handle a situation where you had to manage a high-performing but toxic team member?",
    "Can you discuss an experience where your passion for your work was misconstrued as a negative trait?",
    "Describe a situation where you had to balance your commitment to individual team members with the overall needs of the team.",
    "What would you do if you were to find out that your personal vision was at odds with the company’s strategic goals?",
    "Describe a time when you had to pivot your career path due to unforeseen circumstances.",
    "How would you adapt to a sudden change in corporate strategy that affects your role?",
    "Share an instance where you had to make a decision that had both high risk and high reward.",
    "Discuss an instance where your personal interests conflicted with your professional obligations. How did you resolve it?",
    "Describe a situation where your personal contribution was overlooked. How did you handle it?",
    "How have you navigated the cultural complexities in a multinational work environment?",
    "Describe an instance where you had to adapt your leadership style to meet a team’s needs.",
    "Can you share an experience where you had to adapt to a company culture that you didn’t initially fit into?",
    "How would you handle a high-performing team that is not aligned with the company's cultural values?",
    "Share an experience where you had to motivate a team without any monetary incentives.",
    "Discuss an experience where you had to take a stance against a popular opinion to uphold your values.",
    "Describe how you would handle a situation where you're asked to compromise on the quality of your work.",
    "How would you approach making tough ethical decisions that might put your job at risk?",
    "Share an example of how you’ve managed to maintain your motivation during a prolonged period of uncertainty.",
    "Describe a situation where you had to step in and lead a project that was failing.",
    "Discuss a complex project you managed from conception to completion, focusing on your decision-making process.",
    "Describe an experience where you had to influence organizational change.",
    "How have you navigated power dynamics when you’re not in a position of authority?",
    "Share an experience where you had to confront an issue head-on without support from your superiors.",
    "Describe a situation where your proactive efforts created significant value for an organization.",
    "How would you handle a situation where a colleague is actively undermining your leadership?",
    "Discuss a time when you had to choose between multiple important tasks with conflicting deadlines.",
    "How do you handle it when key team members are not committed to the team’s objectives?",
    "Describe an instance where you successfully advocated for a minority viewpoint.",
    "How would you handle being assigned to a project that conflicts with your personal values?",
    "Describe a situation where you challenged a higher-up and were proven to be correct.",
    "How would you maintain motivation in a team that’s faced with seemingly insurmountable challenges?",
    "Discuss an instance where you took a significant career risk. What was the outcome?",
    "How would you keep your team motivated during a corporate downsizing or restructuring?",
    "Describe a situation where you felt compelled to speak up to protect the interest of your team.",
    "Share an instance where your commitment to work-life balance was tested. How did you resolve it?",
    "What actions would you take to bring a disengaged team back into alignment with the company’s goals?",
    "Describe a project where you had to use your strategic vision to overcome immediate challenges.",
    "How would you adapt if you discovered halfway through a project that your initial assessment was fundamentally flawed?",
    "Describe a situation where you had to take a hard stance against a popular team member.",
    "Discuss an instance where your personal priorities had to take a back seat to urgent professional demands.",
    "Describe a situation where your leadership was essential in overcoming a significant hurdle in a project.",
    "How would you handle a situation where your team’s values are misaligned with corporate goals?",
    "Share a situation where you felt your personal development goals were not supported by the company. How did you address it?",
    "Discuss a complex ethical dilemma you've had to navigate in your professional career.",
    "How would you maintain a culture of continuous improvement in a team resistant to change?",
    "Describe an instance where you made a difficult decision that had an unexpected negative outcome.",
    "How would you inspire a team that’s demoralized due to repeated failures?",
    "Discuss a situation where you had to make a decision without any data or prior experience to rely on.",
    "Share an example of when you had to navigate office politics to get a project approved.",
    "Describe a time when you had to lead a project with a team that was disinterested.",
    "How would you approach a situation where your direct reports are significantly older or more experienced than you?",
    "Describe a situation where you had to resolve a conflict between two strong personalities on your team.",
    "Discuss a time when you had to adapt your communication style to effectively lead your team.",
    "How would you handle a situation where you’re asked to compromise your professional integrity?",
    "Share an instance where you had to be flexible in your role due to organizational changes.",
    "Describe a time when you were faced with an ethical dilemma with no easy solutions.",
    "How would you deal with a toxic but highly productive team member?",
    "Discuss a time when you were given a task outside of your job description that had a significant impact on your team.",
    "Describe a situation where you had to quickly build trust with a new team.",
    "Share an instance where you took on a leadership role without being formally appointed.",
    "How would you approach a situation where you have to manage a team you didn't choose?",
    "Describe a time when you felt like giving up on a project. What kept you going?",
    "Discuss a time when you turned a potential failure into a success.",
    "Share a situation where your commitment to transparency created challenges in a corporate environment.",
    "How would you handle a situation where a superior is making decisions that you believe will negatively affect the team?",
    "Describe a time when you had to lead a team through a highly uncertain period.",
    "Share a situation where you had to make an immediate decision with long-term ramifications.",
    "How would you go about motivating a team that’s demotivated by salary or promotion freezes?",
    "Describe a situation where you faced significant resistance in implementing a new initiative or technology.",
    "Discuss a situation where you had to manage conflicting stakeholder interests.",
    "Share an instance where you had to build a work culture from scratch.",
    "How would you maintain your team’s morale in the face of successive setbacks?",
    "Describe a situation where you had to mediate a conflict between a team member and higher management.",
    "Discuss a project where you had to work closely with a team across different time zones.",
    "Share an instance where you went above and beyond your job description to meet a company’s long-term goals.",
    "Describe a situation where you had to push back against upper management for the good of the project or team.",
    "How would you adapt to a major corporate restructuring in the middle of a critical project?"
]


def get_question(type, difficulty):
    if type == "behavioural" and difficulty == "easy":
        return random.choice(easy_behavioral_questions)

    if type == "behavioural" and difficulty == "medium":
        return random.choice(medium_behavioral_questions)

    if type == "behavioural" and difficulty == "hard":
        return random.choice(hard_behavioral_questions)

    if type == "situational" and difficulty == "easy":
        return random.choice(easy_situational_questions)

    if type == "situational" and difficulty == "medium":
        return random.choice(medium_situational_questions)

    if type == "situational" and difficulty == "hard":
        return random.choice(hard_situational_questions)

    if type == "personal" and difficulty == "easy":
        return random.choice(easy_personal_questions)

    if type == "personal" and difficulty == "medium":
        return random.choice(medium_personal_questions)

    if type == "personal" and difficulty == "hard":
        return random.choice(hard_personal_questions)

    if type == "motivation" and difficulty == "easy":
        return random.choice(easy_motivation_and_fit_questions)

    if type == "motivation" and difficulty == "medium":
        return random.choice(medium_motivation_and_fit_questions)

    if type == "motivation" and difficulty == "hard":
        return random.choice(hard_motivation_and_fit_questions)
    return "Not a valid type"